_$header

_$logical(IncChben,null)
_$integer(NumAgeRng,range)
_$double(MainCou,amount)     
_$double(YngCou,amount)      
_$double(MainLP,amount)      
_$double(YngLP,amount) 
_$double(MainSin,amount)     
_$double(YngSin,amount)    
_$double(ValFSM,amount)
_$double(DisregLP,amount)
_$double(DisregSin,amount) 
_$double(DisregCou,amount)
_$logical(DisregShared,null)
_$double(PremFam,amount)     
_$double(PremLP,amount)      
_$double(hours,range)
_$double(MaintDisreg,amount)
_$integerarray(AgeRngl,range,:)
_$integerarray(AgeRngu,range,:)
_$doublearray(AddKid,amount,:)

_$footer
