_$header

_$logical(dofamcred,null)
_$integer(NumAgeRng,range)
_$integer(MaxAgeCC,range)
_$integer(WFTCMaxAgeCC,range)
_$double(adult,amount)
_$double(ftprem,amount)
_$double(hours1,range)  
_$double(hours2,range)  
_$double(thres,amount)  
_$double(taper,rate)   
_$double(MaintDisreg,amount)
_$double(MaxCC1,amount)
_$double(MaxCC2,amount)  
_$double(WFTCMaxCC1,amount)
_$double(WFTCMaxCC2,amount)
_$double(WFTCPropCC,rate)
_$double(MinAmt,minamount)
_$integerarray(kidagel,range,:)
_$integerarray(kidageu,range,:)
_$doublearray(kidcred,amount,:)  

_$footer