_$header

_$double(Basic,amount)
_$double(CouLP,amount)
_$double(FT,amount)
_$double(MinHrsKids,range)
_$double(MinHrsNoKids,range)
_$double(FTHrs,range)
_$integer(MinAgeKids,range)
_$integer(MinAgeNoKids,range)
_$double(MaxCC1,amount)     
_$double(MaxCC2,amount)         
_$double(PropCC,rate)       
_$integer(MaxAgeCC,range)
_$double(NewDisreg,range)
_$logical(NewDisregCon,null)

_$footer