_$header

_$double(pretaxearn,"Pre-tax earnings",amount)
_$double(posttaxearn,"Post-tax earnings",amount)
_$double(chben,"Child benefit",amount)
_$double(matgrant,"Maternity grant",amount)
_$double(fc,"Family Credit/WFTC",amount)
_$double(wtc,"Working Tax Credit",amount)
_$double(ctc,"Child Tax Credit",amount)
_$double(ccexp,"Childcare expenditure",amount)
_$double(incsup,"Income Support",amount)
_$double(hben,"Housing Benefit",amount)
_$double(polltax,"Community Charge",amount)
_$double(polltaxben,"Community Charge Benefit",amount)
_$double(ctax,"Council Tax",amount)
_$double(ctaxben,"Council Tax Benefit",amount)
_$double(dispinc,"Disposable income",amount)
_$double(pretax,"Pre-tax income",amount)
_$double(nettax,"Total net tax",amount)
_$double(chcaresub,"Childcare subsidy",amount)
_$double(fsm,"Free school meals value",amount)
_$double(totben,"Total benefits and Tax Credits",amount)

_$footer
