_$header
 
_$double(taxable,"Taxable income",amount)
_$double(inctax,"Income tax",amount)
_$double(natins,"National Insurance",amount)
_$double(natinsc1,"National Insurance, class 1",amount)
_$double(natinsc2,"National Insurance, class 2",amount)
_$double(natinsc4,"National Insurance, class 4",amount)
_$double(pretaxearn,"Pre-tax earnings",amount)
_$double(posttaxearn,"Post-tax earnings",amount)

_$footer